---
title: "R Notebook"
output: html_notebook
---
#made some chang


```{r}
library('readxl')
library(xlsx)
setwd(gsub("\\\\","//", readClipboard()))
IIT_crime <- as.data.frame(read_xlsx("Crime_2014toPres_IIT area.xlsx",1))
UC_crime <- as.data.frame(read_xlsx("Crime_2014toPres_UC area.xlsx",1))
IITkent_crime <- as.data.frame(read_xlsx("Crime_2014toPres_Kent area.xlsx",1))

```

```{r}
library(plyr)
dim(IIT_crime)

#Finding the columns which have NA values in them
colnames(IIT_crime)[colSums(is.na(IIT_crime))>0]
IIT_crime[is.na(IIT_crime$`Location Description`),]
unique(IIT_crime$`Location Description`)#Identifying types of Location Descriptions
#Replacing NA value as "OTHER"
IIT_crime[is.na(IIT_crime$`Location Description`), 'Location Description'] <- "OTHER"


head(sort(table(IIT_crime$ID),decreasing = T))
# ID is unique
case_num_IIT <- sort(table(IIT_crime$`Case Number`),decreasing = T)
rep_case_num_IIT <- which(case_num_IIT[]>1)
rep_case_num_IIT <- names(rep_case_num_IIT)

# Case Number are duplicated for 6 unique items (total 13 entries).
IIT_crime[IIT_crime$`Case Number` %in% rep_case_num_IIT,]

#removing the duplicates
IIT_crime <- IIT_crime[!duplicated(IIT_crime$`Case Number`),]


#Dropping attributes unimportant for analysis
#IIT_crime <- IIT_crime[, !(colnames(IIT_crime) %in% c("Beat","District","Ward","Community Area","FBI Code","Updated On", "IUCR", "ID", "Case Number", "Block", "Arrest", "Domestic"))]


```

```{r}
library(lubridate)

# Convert date to YYYY-MM-DD HH:MM format

IIT_crime$Date <- as.POSIXct(IIT_crime$Date, format = "%Y-%m-%d %H:%M", tz = "Europe/London") + hours(5)

# date was taken in GMT added (5/6) hours for conversion as did not work directly

attributes(IIT_crime$Date)$tzone <- "America/Chicago"


```

```{r}

library(reshape2)
library(dplyr)
# identifying types of offences and subtypes and count of each
offences <- sort(table(IIT_crime$`Primary Type`),decreasing = T)

subtype <- sort(table(IIT_crime$Description),decreasing = T)

#IIT_crime[,c('Primary Type','Description')] <- lapply(IIT_crime[c('Primary Type','Description')], factor)


crime_type_count_IIT <- melt(table(IIT_crime[,c('Primary Type','Description')]))
colnames(crime_type_count_IIT)[ncol(crime_type_count_IIT)] <- "count"

crime_type_count_IIT[with(crime_type_count_IIT,order(-count)),]

crime_type_count_IIT <- crime_type_count_IIT[crime_type_count_IIT$count>0,]
crime_type_count_IIT <- crime_type_count_IIT[with(crime_type_count_IIT,order(`Primary Type`)),]


##INCOMPLETE##
##INCOMPLETE##
##INCOMPLETE##
##INCOMPLETE##
##INCOMPLETE##
##INCOMPLETE##

## IGNORE above

#Standardization of incident type
unique(IIT_crime$`Primary Type`)
# PERFORM once only for creating documnet for merging purpose
# write.xlsx(unique(IIT_crime$`Primary Type`), "merge_IIT_Crime.xlsx")

merge_IIT_Crime <- read.xlsx("merge_IIT_Crime.xlsx", sheetIndex = 1)

IITarea_crime_stand <- merge(IIT_crime,merge_IIT_Crime,by.x = "Primary Type", by.y = "x")

#write.csv(IITarea_crime_stand)

```

```{r}
###FOR IIT KENT CAMPUS AREA CRIMES


dim(IITkent_crime)

#Finding the columns which have NA values in them
colnames(IITkent_crime)[colSums(is.na(IITkent_crime))>0]
IITkent_crime[is.na(IITkent_crime$`Location Description`),]
unique(IITkent_crime$`Location Description`)#Identifying types of Location Descriptions
#Replacing NA value as "OTHER"
IITkent_crime[is.na(IITkent_crime$`Location Description`), 'Location Description'] <- "OTHER"


head(sort(table(IITkent_crime$ID),decreasing = T))
# ID is unique
case_num_IITkent <- sort(table(IITkent_crime$`Case Number`),decreasing = T)
rep_case_num_IITkent <- which(case_num_IITkent[]>1)
rep_case_num_IITkent <- names(rep_case_num_IITkent)

# 1 case number is repeated for kent area.
IITkent_crime[IITkent_crime$`Case Number` %in% rep_case_num_IITkent,]


#removing the duplicates
IITkent_crime <- IITkent_crime[!duplicated(IITkent_crime$`Case Number`),]

#FIXING the date
IITkent_crime$Date <- as.POSIXct(IITkent_crime$Date, format = "%Y-%m-%d %H:%M", tz = "Europe/London") + hours(5)

# date was taken in GMT added (5/6) hours for conversion as did not work directly

attributes(IITkent_crime$Date)$tzone <- "America/Chicago"

```


```{r}

#Standardization of incident type
unique(IITkent_crime$`Primary Type`)

#USE once for creating merge table for standardization of incident type
#write.xlsx(unique(IITkent_crime$`Primary Type`),"merge_IITkent_Crime.xlsx")

merge_IITkent_Crime <- read.xlsx("merge_IITkent_Crime.xlsx", sheetIndex = 1)

IITkentarea_crime_stand <- merge(IITkent_crime,merge_IITkent_Crime,by.x = "Primary Type", by.y = "x")

IIT_all_crime_stand <- rbind(IITarea_crime_stand,IITkentarea_crime_stand)


#QUICK Check to see if there is repeat values after merging
head(sort(table(IIT_all_crime_stand$ID),decreasing = T))
#ALL IDs are unique
case_num_IITall <- sort(table(IIT_all_crime_stand$`Case Number`),decreasing = T)
rep_case_num_IITall <- which(case_num_IITall[]>1)
rep_case_num_IITall <- names(rep_case_num_IITall)

IIT_all_crime_stand[IIT_all_crime_stand$`Case Number` %in% rep_case_num_IITall,]

#All case numbers are unique

#Dropping attributes unimportant for analysis
IIT_all_crime_stand <- IIT_all_crime_stand[, !(colnames(IIT_all_crime_stand) %in% c("ID","Case Number","IUCR","Arrest", "Domestic","Beat","District","Ward","Community Area","FBI Code","Updated On"))]

#USE once for writing final file
#write.csv(IIT_all_crime_stand, file = "IITarea_ALL_STAND.csv")

```


```{r}

### FOR UC AREA CRIMES

dim(UC_crime)
# Identifying NA values 
sum(is.na(UC_crime))
colnames(UC_crime)[colSums(is.na(UC_crime))>0]
UC_crime[is.na(UC_crime$`Location Description`),]
# Identifying types of Location Description
unique(UC_crime$`Location Description`)
# Imputing missing data as "OTHER"
UC_crime[is.na(UC_crime$`Location Description`),'Location Description'] <- "OTHER"


```


```{r}
#ID is unqiue
head(sort(table(UC_crime$ID),decreasing = T))
#
case_num_UC <- sort(table(UC_crime$`Case Number`),decreasing = T)
rep_case_num_UC <- which(case_num_UC[]>1)
rep_case_num_UC <- names(rep_case_num_UC)

# Case Number are duplicated for 11 unique items (total 24 entries).
UC_crime[UC_crime$`Case Number` %in% rep_case_num_UC,]

#Removing duplicates
UC_crime <- UC_crime[!duplicated(UC_crime$`Case Number`),]


### NOTE: CRIMES IN IIT MAYBE REPEATED UC AS AREAS OVERLAP

#Dropping attributes unimportant for analysis
#UC_crime <- UC_crime[, !(colnames(UC_crime) %in% c("Beat","District","Ward","Community Area","FBI Code","Updated On", "IUCR"))]

```


```{r}
library(lubridate)

# Convert date to YYYY-MM-DD HH:MM format

UC_crime$Date <- as.POSIXct(UC_crime$Date, format = "%Y-%m-%d %H:%M", tz = "Europe/London") + hours(5)

# date was taken in GMT added (5/6) hours for conversion as did not work directly

attributes(UC_crime$Date)$tzone <- "America/Chicago"

```

```{r}
library(reshape2)
library(dplyr)
# identifying types of offences and subtypes and count of each
#offences_UC <- sort(table(UC_crime$`Primary Type`),decreasing = T)

#subtype_UC <- sort(table(UC_crime$Description),decreasing = T)

#IIT_crime[,c('Primary Type','Description')] <- lapply(IIT_crime[c('Primary Type','Description')], factor)


#crime_type_count_UC <- melt(table(UC_crime[,c('Primary Type','Description')]))
#colnames(crime_type_count_UC)[ncol(crime_type_count_UC)] <- "count"

#crime_type_count_UC[with(crime_type_count_UC,order(-count)),]

#crime_type_count_UC <- crime_type_count_UC[crime_type_count_UC$count>0,]
#crime_type_count_UC <- crime_type_count_UC[with(crime_type_count_UC,order(`Primary Type`)),]

unique(UC_crime$`Primary Type`)

write.xlsx(unique(UC_crime$`Primary Type`),file = "merge_UC_Crime.xlsx")

merge_UC_Crime <- read.xlsx("merge_UC_Crime.xlsx", sheetIndex = 1)

UCarea_crime_stand <- merge(UC_crime,merge_UC_Crime,by.x = "Primary Type", by.y = "x")

UCarea_crime_stand <- UCarea_crime_stand[, !(colnames(UCarea_crime_stand) %in% c("ID","Case Number","IUCR","Arrest", "Domestic","Beat","District","Ward","Community Area","FBI Code","Updated On"))]


write.csv(UCarea_crime_stand,file = "UCarea_STAND.csv")
```

```{r}
#LAT LONG 

library(ggmap)
coordinates <- function(x){
  
  temp<-geocode(x, output='all', messaging=TRUE, override_limit=TRUE)
  while(temp$status == "OVER_QUERY_LIMIT"){
   
    Sys.sleep(3)
    temp = geocode(address, output='all', messaging=TRUE, override_limit=TRUE)
    
  }
  
  
  Latitude <- temp$results[[1]]$geometry$location$lat
  Longitude <- temp$results[[1]]$geometry$location$lng 
  
  return(c(Latitude,Longitude))
  
}

#coordinates("565 W Adams St Chicago IL 60661")
```

